baseURL = "http://tigersoup.net/"
languageCode = "en-us"
title = "Tiger Soup"
theme = "ananke"
publishDir = "docs"
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "#"
    weight = -10
  [[menu.main]]
    parent = "about"
    name = "Tiger Soup"
    url = "/about/introduction/"
    weight = 1
  [[menu.main]]
    parent = "about"
    name = "What we do"
    url = "/about/wwd/"
    weight = 2
  [[menu.main]]
    parent = "about"
    name = "New Challenges"
    url = "/about/challenges/"
    weight = 3
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    title = "Contact"
    url = "/contact/"
    weight = -8
  [[menu.main]]
    identifier = "fable"
    name = "A Fable"
    title = "Fable"
    url = "/story/"
    weight = -7
[params]
    custom_js = ["/js/main.js"]
