baseURL = "http://sumitii.github.io/tigersoup/"
languageCode = "en-us"
title = "TigerSoup"
theme = "ananke"
publishDir = "docs"
[params]
    custom_css = ["/css/navigation.css", "/css/index.css"]
    custom_js = ["/js/main.js"]
